// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN232.Lab2.CoffeeStore.Repositories.Entities;

public partial class Order
{
    public int OrderId { get; set; }

    public string UserId { get; set; }

    public DateTime? OrderDate { get; set; } = DateTime.Now;

    public string Status { get; set; }

    public int? PaymentId { get; set; }

    public bool? IsActive { get; set; } = true;

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual Payment Payment { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}