// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN232.Lab2.CoffeeStore.Repositories.Entities;

public partial class Payment
{
    public int PaymentId { get; set; }

    public int? OrderId { get; set; }

    public decimal Amount { get; set; }

    public DateTime? PaymentDate { get; set; } = DateTime.Now;

    public string PaymentMethod { get; set; }

    public bool? IsActive { get; set; } = true;

    public virtual Order Order { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}