// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PRN232.Lab2.CoffeeStore.Repositories.Entities;

public partial class Product
{
    public int ProductId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal Price { get; set; }

    public int? CategoryId { get; set; }

    public bool? IsActive { get; set; } = true;

    public virtual Category Category { get; set; } 

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}